name = "bsc-v2"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-22"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
# Replace this with the id returned by `wrangler hyperdrive create`.
id = "9944fb40c5704b66abf6f5070ea5bb71"
